In [2]:
# import library and module
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
from google.colab import files
uploaded = files.upload()

Saving PotatoPrice.csv to PotatoPrice.csv


In [4]:
df = pd.read_csv('PotatoPrice.csv')

In [5]:
X = df[['potato_kg']]
Y = df['price']

In [6]:
X

potato_kg
0          1
1          2
2          3
3          4
4          5
5          6
6          7
7          8
8          9
9         10

In [7]:
# Split Dataset for Train and Test
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train, Y_test = train_test_split(X,Y, test_size=0.3)
# X_train

In [8]:
X_train

potato_kg
4          5
6          7
8          9
2          3
5          6
1          2
9         10

In [9]:
# ANN Model Building
model = tf.keras.Sequential([
       tf.keras.layers. Dense (1, input_shape=[1], activation='linear')
])
# model.summary()

In [10]:
# Compile The ANN model
model.compile(optimizer='sgd',
             loss='mean_squared_error',
             metrics=['accuracy'])

In [11]:
#Train ANN Model
model.fit(X_train,Y_train, epochs=400)

Epoch 1/400
1/1 [==============================] - 1s 618ms/step - loss: 6860.8193 - accuracy: 0.0000e+00
Epoch 2/400
1/1 [==============================] - 0s 11ms/step - loss: 131.0258 - accuracy: 0.0000e+00
Epoch 3/400
1/1 [==============================] - 0s 17ms/step - loss: 42.2045 - accuracy: 0.0000e+00
Epoch 4/400
1/1 [==============================] - 0s 10ms/step - loss: 40.8834 - accuracy: 0.0000e+00
Epoch 5/400
1/1 [==============================] - 0s 9ms/step - loss: 40.7163 - accuracy: 0.0000e+00
Epoch 6/400
1/1 [==============================] - 0s 10ms/step - loss: 40.5653 - accuracy: 0.0000e+00
Epoch 7/400
1/1 [==============================] - 0s 11ms/step - loss: 40.4155 - accuracy: 0.0000e+00
Epoch 8/400
1/1 [==============================] - 0s 11ms/step - loss: 40.2668 - accuracy: 0.0000e+00
Epoch 9/400
1/1 [==============================] - 0s 18ms/step - loss: 40.1190 - accuracy: 0.0000e+00
Epoch 10/400
1/1 [==============================] - 0s 9ms/step - loss

In [12]:
X_test

potato_kg
7          8
3          4
0          1

In [13]:
#Predict
model.predict(X_test)
# X_test

1/1 [==============================] - 0s 80ms/step


array([[98.2122   ],
       [45.661488 ],
       [ 6.2484517]], dtype=float32)

In [14]:
#Predict the Outout Manually
model.predict([[16]])

1/1 [==============================] - 0s 35ms/step


array([[203.31363]], dtype=float32)

In [15]:
#Predict the Outout Manually
model.predict([[6]])

1/1 [==============================] - 0s 32ms/step


array([[71.93684]], dtype=float32)

In [16]:
#Predict the Outout Manually
model.predict([[1]])

1/1 [==============================] - 0s 42ms/step


array([[6.2484517]], dtype=float32)